name: Events Demo
on:
  push:
    branches:
      # - "main"
      - "master"
  pull_request:
    types:
      - "opened"
      - "edited"
      - "closed"
    branches:
      - "main"
      - "master"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get github event
        run: echo "${{ toJSON(github.event) }}"
      - name: Install Dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: test code
        run: npm run test
      - name: build code
        run: npm run build
      - name: deploy
        run: |
          echo The code tests are satisfactory
          echo The code is been deployed ...