name: Lint Test
on: workflow_dispatch
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: test code
        run: npm run test
      - name: build code
        run: npm run build
      - name: deploy
        run: |
          echo The code is been deployed ...